services:
  postgres:
    image: postgres:15
    container_name: postgres-workshop
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      WORKSHOP_DB_NAME: jesus_maria_workshops
      WORKSHOP_DB_USER: workshop_user
      WORKSHOP_DB_PASSWORD: workshop_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./workshop-data:/workshop-data
    networks:
      - workshop-network
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U workshop_user -d jesus_maria_workshops"]
      interval: 30s
      timeout: 10s
      retries: 3

  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master-workshop
    hostname: spark-master
    ports:
      - "8080:8080" # Spark Web UI
      - "7077:7077" # Spark Master Port
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./workshop-data:/opt/workshop-data
      - spark_events:/tmp/spark-events
    networks:
      - workshop-network
    depends_on:
      postgres:
        condition: service_healthy

  spark-worker-1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-1
    hostname: spark-worker-1
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_WEBUI_PORT=8081
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./workshop-data:/opt/workshop-data
    networks:
      - workshop-network
    depends_on:
      - spark-master

  spark-worker-2:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-2
    hostname: spark-worker-2
    ports:
      - "8082:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_WEBUI_PORT=8081
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./workshop-data:/opt/workshop-data
    networks:
      - workshop-network
    depends_on:
      - spark-master

  jupyter-workshop:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyter-workshop
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_MASTER=spark://spark-master:7077
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=jesus_maria_workshops
      - POSTGRES_USER=workshop_user
      - POSTGRES_PASSWORD=workshop_pass
    volumes:
      - ./notebooks:/home/jlorenzor/work
      - ./workshop-data:/home/jlorenzor/data
      - ./scripts:/home/jlorenzor/scripts
      - ./spark-apps:/home/jlorenzor/apps
    networks:
      - workshop-network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  workshop-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  postgres_data:
    driver: local
  spark_events:
    driver: local
