version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: workshop-postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-jesus_maria_workshops}
      POSTGRES_USER: ${POSTGRES_USER:-workshop_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-workshop_pass}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/workshop-data
    networks:
      - workshop-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-workshop_user} -d ${POSTGRES_DB:-jesus_maria_workshops}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Spark Master
  spark-master:
    build:
      context: ./docker
      dockerfile: Dockerfile.spark
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"  # Spark Web UI
      - "7077:7077"  # Spark Master Port
      - "4040:4040"  # Spark Application UI
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    volumes:
      - ./src:/opt/spark-apps
      - ./data:/opt/workshop-data
      - ./docker/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - spark_logs:/opt/spark/logs
    networks:
      - workshop-network
    depends_on:
      postgres:
        condition: service_healthy

  # Spark Worker 1
  spark-worker-1:
    build:
      context: ./docker
      dockerfile: Dockerfile.spark
    container_name: spark-worker-1
    hostname: spark-worker-1
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_WEBUI_PORT=8081
    volumes:
      - ./src:/opt/spark-apps
      - ./data:/opt/workshop-data
      - ./docker/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    networks:
      - workshop-network
    depends_on:
      - spark-master

  # Spark Worker 2
  spark-worker-2:
    build:
      context: ./docker
      dockerfile: Dockerfile.spark
    container_name: spark-worker-2
    hostname: spark-worker-2
    ports:
      - "8082:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_WEBUI_PORT=8081
    volumes:
      - ./src:/opt/spark-apps
      - ./data:/opt/workshop-data
      - ./docker/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    networks:
      - workshop-network
    depends_on:
      - spark-master

  # Jupyter Lab for Interactive Development
  jupyter:
    build:
      context: ./docker
      dockerfile: Dockerfile.jupyter
    container_name: workshop-jupyter
    hostname: jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=workshop2025
      - GRANT_SUDO=yes
      - SPARK_MASTER=spark://spark-master:7077
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB:-jesus_maria_workshops}
      - POSTGRES_USER=${POSTGRES_USER:-workshop_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-workshop_pass}
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./src:/home/jovyan/apps
      - ./scripts:/home/jovyan/scripts
    networks:
      - workshop-network
    depends_on:
      postgres:
        condition: service_healthy

  # PgAdmin para administración de BD (opcional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: workshop-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@workshop.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - workshop-network
    depends_on:
      - postgres

networks:
  workshop-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  spark_logs:
    driver: local